-- Generated editorial aliases only; contains no government facts.
insert into public.query_aliases(alias,resource_key) values
('yks ek tercih','yks_extra'),
('yks ikinci tercih','yks_extra'),
('yks ek yerlestirme','yks_extra'),
('ek yerlestirme','yks_extra'),
('ek tercih','yks_extra'),
('yks tercih','yks_preferences'),
('yks tercihleri','yks_preferences'),
('universite tercihleri','yks_preferences'),
('yks sonuc','yks_results'),
('yks sonuclari','yks_results'),
('dgs tercih','dgs_preferences'),
('dgs tercihleri','dgs_preferences'),
('dikey gecis tercihleri','dgs_preferences'),
('kpss ortaogretim sinav','kpss_exam'),
('kpss lise sinav','kpss_exam'),
('ortaogretim kpss','kpss_exam'),
('lgs','lgs_exam'),
('lgs sinav','lgs_exam'),
('liselere gecis sinavi','lgs_exam'),
('kyk yurt sonuclari','kyk_results'),
('kyk yurtlari','kyk_results'),
('kyk yurt sonuc','kyk_results'),
('yurt sonuclari','kyk_results'),
('kyk yurt basvuru','kyk_applications'),
('kyk yurt basvurulari','kyk_applications'),
('yurt basvurulari','kyk_applications'),
('yks yerlestirme sonuclari','yks_placement_results'),
('yks yerlestirme sonuc','yks_placement_results'),
('universite yerlestirme sonuclari','yks_placement_results'),
('yks ek yerlestirme sonuclari','yks_extra_results'),
('yks ek yerlestirme sonuc','yks_extra_results'),
('ek yerlestirme sonuclari','yks_extra_results')
on conflict(alias) do update set resource_key=excluded.resource_key;
